[2024-12-08 11:26:03,952] INFO _log() L97   127.0.0.1 - - [08/Dec/2024 11:26:03] "[31m[1mPOST /progressao HTTP/1.1[0m" 400 - - call_trace=c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-08 11:26:24,847] WARNING add_progressao() L67   Erro ao adicionar progressão '33' - 'teste', Não foi possível salvar novo item :/ - call_trace=C:\Users\rafga\git\mvp-api\app.py L67  
[2024-12-08 11:26:24,850] INFO _log() L97   127.0.0.1 - - [08/Dec/2024 11:26:24] "[31m[1mPOST /progressao HTTP/1.1[0m" 400 - - call_trace=c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-08 11:45:37,013] ERROR log_exception() L875  Exception on /progressoes [GET] - call_trace=c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "C:\Users\rafga\git\mvp-api\app.py", line 82, in get_progressoes
    progressoes = session.query(Progressao).all()
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ~~~~~~~~~~^^
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
        params,
        ^^^^^^^
        execution_options={"_sa_orm_load_options": self.load_options},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2362, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2237, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2106, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3278, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3302, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
  File "c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 168, in _do_get
    raise exc.TimeoutError(
    ...<4 lines>...
    )
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[2024-12-08 11:45:37,069] INFO _log() L97   127.0.0.1 - - [08/Dec/2024 11:45:37] "[35m[1mGET /progressoes HTTP/1.1[0m" 500 - - call_trace=c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-08 11:45:46,517] WARNING add_progressao() L67   Erro ao adicionar progressão '45' - 'teste teste', Não foi possível salvar novo item :/ - call_trace=C:\Users\rafga\git\mvp-api\app.py L67  
[2024-12-08 11:45:46,521] INFO _log() L97   127.0.0.1 - - [08/Dec/2024 11:45:46] "[31m[1mPOST /progressao HTTP/1.1[0m" 400 - - call_trace=c:\Users\rafga\git\mvp-api\.venv\Lib\site-packages\werkzeug\_internal.py L97  
